global using System;
global using System.Buffers;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO.Compression;
global using System.IO.MemoryMappedFiles;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Net.Mime;
global using System.Net.Security;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using LibGit2Sharp;
global using Microsoft.Win32.SafeHandles;
global using NanosWorld;
global using Tomlyn;
global using Tomlyn.Model;
global using c = System.Console;
global using J = System.Text.Json.Serialization.JsonPropertyNameAttribute;
global using N = System.Text.Json.Serialization.JsonIgnoreCondition;
global using Version = System.Version;
