-- <auto-generated> This file has been auto generated. </auto-generated>

---@class metadata_gen
---@field package_version string
---@field timestamp string
---@field commit_count integer
---@field tag_count integer
---@field branch_name string
---@field prev_hash string
---@field tag string
---@field owner string
---@field repo string
---@field path string
---@field filenames_hash string
---@field files_hash table<string, string>
---@field files string[]

---@type metadata_gen
return {
	package_version = "0.0.1",
	timestamp = "2026-05-08 10:57:17",
	commit_count = 272,
	tag_count = 39,
	branch_name = "main",
	prev_hash = "98c5be1a78f883136c3ab7774a41288c8173ddd3",
	tag = "v0.0.43",
	owner = "Cheatoid",
	repo = "nanos-world-vault",
	path = "anticheat",
	filenames_hash = "d891634bae53f90ab9182beeaa98c41e59e1be114585ca9e998be58ca4f2fa44",
	files_hash = {
		["Package.toml"] = "057bbbf8c3cf51008757c4370282ce164daac7ae0deb6b445dff161b7e37187a",
		["index.html"] = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		["Client/Index.lua"] = "850d7813cfcccd36357cc4dba42914c35617340067a8318f4ac6adec0157de14",
		["Server/Index.lua"] = "cb3799c7c6a577c1c26ffbe9d8fb814e8c361c59a663a0005234a3b33c83981b",
		["Shared/Config.lua"] = "a9453d0f990cd36c3a6538612736c4112c2c0c109793ae09b85c9b6f4b43008e",
		["Shared/Index.lua"] = "e8c904ba8041eab2b2bf9760a45a6cbbf9dd99f56a47917105a3feb8140ddf80"
	},
	files = {
		"Package.toml",
		"index.html",
		"Client/Index.lua",
		"Server/Index.lua",
		"Shared/Config.lua",
		"Shared/Index.lua",
		"Shared/metadata_gen.lua",
	},
}
